# Settings when running in "dev" (as opposed to prod)
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ALL
  # Logger-specific levels.
  loggers:
    "io.dropwizard": INFO
    "javax.management": INFO
    "org.eclipse.jetty": INFO
    "org.glassfish.jersey": INFO
    "org.jvnet.hk2": INFO
    "sun.rmi.transport": INFO
  appenders:
    - type: console
      threshold: ALL
      target: stdout
server:
  applicationConnectors:
    -
      type: http
      # The hostname of the interface to which the HTTP server socket
      # will be bound. If omitted, the socket will listen on all
      # interfaces.
      bindHost: localhost
freemarkerTemplateDir: "src/main/resources/freemarker"
devMode: true